"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py

# --- Browser-Side Protections ---

# 1. X-Frame-Options (Clickjacking Prevention)
# 'DENY' prevents your site from being embedded in a frame, iframe, embed, or object.
# Use 'SAMEORIGIN' if you need framing for content from the same domain.
X_FRAME_OPTIONS = 'DENY' 

# 2. X-Content-Type-Options (MIME-sniffing Prevention)
# Stops browsers from trying to guess the content type, preventing certain XSS attacks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# 3. X-XSS-Protection (Legacy XSS Filter)
# Activates the browser's built-in Cross-Site Scripting filter.
# Note: CSP is the modern and more robust alternative.
SECURE_BROWSER_XSS_FILTER = True


# --- Secure Cookie Configuration (Requires HTTPS) ---

# 4. CSRF Cookie Security
# Ensures the CSRF token cookie is only transmitted over HTTPS connections.
CSRF_COOKIE_SECURE = True

# 5. Session Cookie Security
# Ensures the session ID cookie is only transmitted over HTTPS connections.
SESSION_COOKIE_SECURE = True

# LibraryProject/settings.py

# --- Content Security Policy (CSP) Configuration ---
# Set the default allowed source to only the current domain ('self')
CSP_DEFAULT_SRC = ("'self'",)

# Scripts are only allowed from the current domain
CSP_SCRIPT_SRC = ("'self'",) 

# Styles are allowed from the current domain and one external source (e.g., Google Fonts)
CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com') 

# Images allowed from current domain
CSP_IMG_SRC = ("'self'",)

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1*gu^zjk&2kvx#el%&b0i$zp=9w)+&*t-_g^upmsoaq01r#c7%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.yourdomain.com', '127.0.0.1', 'localhost']


# Application definition
#customuser models
AUTH_USER_MODEL='bookshelf.CustomUser'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.CustomUser',
    'relationship_app',
]

MIDDLEWARE = [
    'django.csp.middleware.CspMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
